name: Deploy Codedoc Documentation

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not `main`

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the version of Node.js you are using

    - name: Install dependencies
      run: npm install

    - name: Build documentation
      run: codedoc build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs/dist
